# Generated by Django 5.0.4 on 2024-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
